spring.application.name=carrito

spring.datasource.url=jdbc:mysql://localhost:3306/carrito_compras
spring.datasource.username=root
spring.datasource.password=Mysql2026!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false